version: "3"
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_DB: model-test
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
    # volumes:
    #   - "$HOME/db-data/:/var/lib/postgresql/data"
  build-data:
    image: chughto/testmodels:build-data
    environment:
      PGHOST: db
      PGUSER: root
      PGDATABASE: model-test
      PGPASSWORD: password
  test-textblob:
    image: chughto/testmodels:textblob
    environment:
      PGHOST: db
      PGUSER: root
      PGDATABASE: model-test
      PGPASSWORD: password
  # test-flair:
  #   image: chughto/testmodels:flair
  #   environment:
  #     PGHOST: db
  #     PGUSER: root
  #     PGDATABASE: model-test
  #     PGPASSWORD: password
  test-vader:
    image: chughto/testmodels:vader
    environment:
      PGHOST: db
      PGUSER: root
      PGDATABASE: model-test
      PGPASSWORD: password
  test-random:
    image: chughto/testmodels:random
    environment:
      PGHOST: db
      PGUSER: root
      PGDATABASE: model-test
      PGPASSWORD: password
  calc-metrics:
    image: chughto/testmodels:calcmetrics
    environment:
      PGHOST: db
      PGUSER: root
      PGDATABASE: model-test
      PGPASSWORD: password
  dash:
    image: chughto/testmodels:dash
    environment:
      PGHOST: db
      PGUSER: root
      PGDATABASE: model-test
      PGPASSWORD: password
    ports:
      - 8080:8080

# volumes:
#   dbdata:
#     driver: local
